# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: npm package

on:
    release:
        types: [created]

jobs:
    publish-npm:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: pnpm/action-setup@v4
              with:
                  version: 10
            - uses: actions/setup-node@v3
              with:
                  node-version: 22.14.0
                  registry-url: https://registry.npmjs.org/
            - run: pnpm i --frozen-lockfile
            - run: pnpm clean
            - run: pnpm build
            - run: npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
